### PR TITLE
Cruster 0.7.2 - config: fix cer_path exists

### PR DESCRIPTION
**Pull request by wst7**

### CODE REVIEW

**Comment by sinKettu** [comment]
@wstreet Hello! Thank you a lot for your fix. Could you please change your commit message for others' commits stile? For example, `Cruster 0.7.2 - config: fix cer_path exists`?

**Comment by wstreet** [comment]
Yes, I will make the changes later.

**Comment by wstreet** [comment]
> @wstreet Hello! Thank you a lot for your fix. Could you please change your commit message for others' commits stile? For example, `Cruster 0.7.2 - config: fix cer_path exists`?

Yes, I will make the changes later.

**Comment by sinKettu** [comment]
Thank you so much!

**Pull request merged**
